definitions:
  entity.ExampleCreateRequest:
    properties:
      name:
        type: string
    required:
    - name
    type: object
  entity.ExampleItemResponse:
    properties:
      id:
        type: integer
      name:
        type: string
    type: object
  entity.ExampleListResponse:
    properties:
      current:
        type: integer
      items:
        items:
          $ref: '#/definitions/entity.ExampleItemResponse'
        type: array
      size:
        type: integer
      total:
        type: integer
    type: object
  entity.ExampleUpdateRequest:
    properties:
      id:
        type: integer
      name:
        type: string
    required:
    - id
    - name
    type: object
info:
  contact: {}
paths:
  /api/internal/example:
    post:
      consumes:
      - application/json
      parameters:
      - description: entity
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/entity.ExampleCreateRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema: {}
      tags:
      - Example
    put:
      consumes:
      - application/json
      parameters:
      - description: entity
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/entity.ExampleUpdateRequest'
      produces:
      - application/json
      - application/json
      responses:
        "200":
          description: OK
          schema: {}
      tags:
      - Example
  /api/internal/example/{id}:
    delete:
      consumes:
      - application/json
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema: {}
      tags:
      - Example
    get:
      consumes:
      - application/json
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.ExampleItemResponse'
      tags:
      - Example
  /api/internal/example/list:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.ExampleListResponse'
      tags:
      - Example
  /api/public/example/hello:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema: {}
      tags:
      - Example
swagger: "2.0"
