definitions:
  entity.ExampleEntity:
    properties:
      name:
        type: string
    type: object
  entity.ExampleListEntity:
    properties:
      current:
        type: integer
      items:
        items:
          $ref: '#/definitions/entity.ExampleWrapperEntity'
        type: array
      size:
        type: integer
      total:
        type: integer
    type: object
  entity.ExampleWrapperEntity:
    properties:
      id:
        type: integer
      name:
        type: string
    type: object
info:
  contact: {}
paths:
  /api/v1/example:
    post:
      consumes:
      - application/json
      parameters:
      - description: entity
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/entity.ExampleEntity'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema: {}
      tags:
      - Example
    put:
      consumes:
      - application/json
      parameters:
      - description: entity
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/entity.ExampleWrapperEntity'
      produces:
      - application/json
      - application/json
      responses:
        "200":
          description: OK
          schema: {}
      tags:
      - Example
  /api/v1/example/{id}:
    delete:
      consumes:
      - application/json
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema: {}
      tags:
      - Example
    get:
      consumes:
      - application/json
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.ExampleWrapperEntity'
      tags:
      - Example
  /api/v1/example/hello:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema: {}
      tags:
      - Example
  /api/v1/example/list:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.ExampleListEntity'
      tags:
      - Example
swagger: "2.0"
