definitions:
  entity.CloudRegionCreateRequest:
    properties:
      introduction:
        type: string
      name:
        type: string
    required:
    - name
    type: object
  entity.CloudRegionItemResponse:
    properties:
      id:
        type: integer
      introduction:
        type: string
      name:
        type: string
    type: object
  entity.CloudRegionUpdateRequest:
    properties:
      id:
        type: integer
      introduction:
        type: string
      name:
        type: string
    required:
    - id
    - name
    type: object
  entity.CollectorCreateRequest:
    properties:
      description:
        type: string
      details:
        type: string
      name:
        type: string
      operating_system:
        type: string
    required:
    - description
    - details
    - name
    - operating_system
    type: object
  entity.CollectorItemResponse:
    properties:
      description:
        type: string
      details:
        type: string
      id:
        type: integer
      name:
        type: string
      operating_system:
        type: string
    type: object
  entity.VariableCreateRequest:
    properties:
      cloud_region_id:
        type: integer
      description:
        type: string
      name:
        type: string
      value:
        type: string
    required:
    - name
    - value
    type: object
  entity.VariableItemResponse:
    properties:
      description:
        type: string
      id:
        type: string
      name:
        type: string
      value:
        type: string
    type: object
  entity.VariableUpdateRequest:
    properties:
      description:
        type: string
      id:
        type: integer
      name:
        type: string
      value:
        type: string
    required:
    - id
    - name
    - value
    type: object
info:
  contact: {}
paths:
  /node-manager/internal/cloud-region/create:
    post:
      consumes:
      - application/json
      parameters:
      - description: entity
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/entity.CloudRegionCreateRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema: {}
      summary: 创建云区域
      tags:
      - CloudRegion
  /node-manager/internal/cloud-region/list:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/entity.CloudRegionItemResponse'
            type: array
      summary: 获取所有云区域
      tags:
      - CloudRegion
  /node-manager/internal/cloud-region/update:
    put:
      consumes:
      - application/json
      parameters:
      - description: entity
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/entity.CloudRegionUpdateRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema: {}
      summary: 更新云区域
      tags:
      - CloudRegion
  /node-manager/internal/collector/create:
    post:
      consumes:
      - application/json
      parameters:
      - description: entity
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/entity.CollectorCreateRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema: {}
      summary: 创建采集器
      tags:
      - Collector
  /node-manager/internal/collector/list:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/entity.CollectorItemResponse'
            type: array
      summary: 获取采集器列表
      tags:
      - Collector
  /node-manager/internal/variable/create:
    post:
      consumes:
      - application/json
      parameters:
      - description: entity
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/entity.VariableCreateRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema: {}
      summary: 创建变量
      tags:
      - Variable
  /node-manager/internal/variable/delete/multiple:
    delete:
      consumes:
      - application/json
      parameters:
      - description: Variable IDs
        in: body
        name: ids
        required: true
        schema:
          items:
            type: integer
          type: array
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema: {}
      summary: 删除多个变量
      tags:
      - Variable
  /node-manager/internal/variable/delete/single/{id}:
    delete:
      consumes:
      - application/json
      parameters:
      - description: Variable ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema: {}
      summary: 删除单个变量
      tags:
      - Variable
  /node-manager/internal/variable/list/{cloudRegionId}:
    get:
      consumes:
      - application/json
      parameters:
      - description: Cloud Region ID
        in: path
        name: cloudRegionId
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/entity.VariableItemResponse'
            type: array
      summary: 获取该云区域下的所有变量
      tags:
      - Variable
  /node-manager/internal/variable/search/{cloudRegionId}:
    get:
      consumes:
      - application/json
      parameters:
      - description: Cloud Region ID
        in: path
        name: cloudRegionId
        required: true
        type: integer
      - description: Search Value
        in: query
        name: value
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/entity.VariableItemResponse'
            type: array
      summary: 搜索该云区域下的变量
      tags:
      - Variable
  /node-manager/internal/variable/update:
    put:
      consumes:
      - application/json
      parameters:
      - description: entity
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/entity.VariableUpdateRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema: {}
      summary: 更新变量
      tags:
      - Variable
swagger: "2.0"
